# Generated by Django 4.0.3 on 2022-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfamilia', '0002_familiares_cumple_familiares_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
